version: "3.1"
services:
    www:
        image: localhost/visualhud
        ports: 
            - 80:80
        volumes:
            - ./www:/var/www/html/visualhud
            - ./temp:/tmp/visualhud/_temp
        networks:
            - default