services:
    www:
        image: ghcr.io/dmitry-osin/quakelive-visual-hud:latest
        ports: 
            - 80:80
        volumes:
            - ./www:/var/www/html/visualhud
            - ./temp:/tmp/visualhud/_temp
        networks:
            - default